import { SummaryResult } from '../types';

/**
 * Downloads the summary as an HTML file.
 * This is the most reliable way to "Save" the report without a backend.
 */
export const downloadDigestAsHtml = (summaries: SummaryResult[]) => {
  const today = new Date().toLocaleDateString('zh-CN');
  
  const htmlContent = `
    <html>
      <head>
        <title>AI Podcast Digest - ${today}</title>
        <style>
          body { font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #333; }
          .episode { border-bottom: 1px solid #eee; padding-bottom: 20px; margin-bottom: 20px; }
          .title { font-size: 1.5em; font-weight: bold; color: #2563eb; }
          .meta { font-size: 0.9em; color: #666; margin-bottom: 10px; }
          .section { margin-top: 10px; }
          .label { font-weight: bold; font-size: 0.9em; color: #555; text-transform: uppercase; }
          .key-points { background: #f8fafc; padding: 15px; border-radius: 8px; }
          .error { color: red; background: #fee2e2; padding: 10px; }
        </style>
      </head>
      <body>
        <h1>📅 Podcast Digest: ${today}</h1>
        ${summaries.map(s => `
          <div class="episode">
            <div class="meta">${s.podcastName}</div>
            <div class="title">
              <a href="${s.originalLink}">${s.translatedTitle}</a>
            </div>
            <div class="meta">${s.originalTitle}</div>
            
            ${s.translatedTitle.includes('Failed') ? 
              `<div class="error">${s.summaryChinese}</div>` : 
              `
                <div class="section">
                  <div class="label">Summary (CN)</div>
                  <p>${s.summaryChinese}</p>
                </div>
                <div class="section">
                  <div class="label">Summary (EN)</div>
                  <p>${s.summaryEnglish}</p>
                </div>
                <div class="section key-points">
                  <div class="label">Key Takeaways</div>
                  <ul>
                    ${s.keyPoints.map(k => `<li>${k}</li>`).join('')}
                  </ul>
                </div>
              `
            }
          </div>
        `).join('')}
        <div style="margin-top: 40px; font-size: 0.8em; color: #888; text-align: center;">
          Generated by Gemini 2.5 AI Digest
        </div>
      </body>
    </html>
  `;

  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `podcast-digest-${today.replace(/\//g, '-')}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const sendEmailDigest = async (email: string, summaries: SummaryResult[]): Promise<boolean> => {
  // We use mailto to open the client. 
  // NOTE: mailto links have a length limit (approx 2000 chars).
  // We must truncate the content or it will fail to open.
  
  const subject = encodeURIComponent(`🎙️ AI Podcast Digest - ${new Date().toLocaleDateString()}`);
  
  let bodyText = `Here is your daily podcast summary:\n\n`;
  
  summaries.forEach((s) => {
    bodyText += `== ${s.podcastName} ==\n`;
    bodyText += `${s.translatedTitle}\n`;
    bodyText += `${s.originalLink}\n\n`;
    bodyText += `Summary: ${s.summaryChinese.substring(0, 150)}...\n\n`; // Truncate for mailto safety
  });
  
  bodyText += `\n(See attached or full report in app)`;

  const mailtoLink = `mailto:${email}?subject=${subject}&body=${encodeURIComponent(bodyText)}`;
  
  // Create a temporary link to trigger the mail client
  const a = document.createElement('a');
  a.href = mailtoLink;
  a.click();
  
  return true; // "Sent" in the sense that we triggered the action
};

export const copyDigestToClipboard = async (summaries: SummaryResult[]): Promise<void> => {
  const today = new Date().toLocaleDateString();
  let body = `AI Podcast Digest - ${today}\n\n`;
  
  summaries.forEach((s) => {
    body += `🎙️ ${s.podcastName}\n`;
    body += `📄 ${s.translatedTitle}\n`;
    body += `🔗 ${s.originalLink}\n\n`;
    body += `${s.summaryChinese}\n\n`;
    body += `Key Points:\n${s.keyPoints.map(k => `• ${k}`).join('\n')}\n`;
    body += `\n──────────────────────────\n\n`;
  });

  await navigator.clipboard.writeText(body);
};